# This is a basic workflow to help you get started with Actions

name: "Validate Example: Basic"

# Controls when the action will run. 
on: 
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.terraform.lock.hcl'
      - 'LICENSE'
      - 'README.md'
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Test with Checkov
      # You may pin to the exact commit or the version.
      # uses: bridgecrewio/checkov-action@00cc657f4d415593e5c8897bc87f490497ccb5f9
      uses: bridgecrewio/checkov-action@v12.641.0
      with:
        # directory with infrastructure code to scan
        directory: ./examples/basic
        framework: terraform
        log_level: error
